spring:
  profiles:
    active: test
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_quartz?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 2017yang
    validationQuery: select 1
    testOnBorrow: true
    minPoolSize: 2
    maxPoolSize: 10
    # 最大空闲时间 c3p0.maxIdleTime=hibernate.c3p0.timeout
    maxIdleTime: 3600
    # 当连接池中的连接耗尽的时候c3p0一次同时获取的连接数。默认值: 3
    acquireIncrement: 3
    maxStatements: 1000
    initialPoolSize: 3
    # 每1800秒检查所有连接池中的空闲连接。Default: 0
    idleConnectionTestPeriod: 60
    acquireRetryAttempts: 30
    # 重新尝试的时间间隔，默认为：1000毫秒
    acquireRetryDelay: 1000
    breakAfterAcquireFailure: false
    # 获取连接时测试有效性，每次都验证连接是否可用
    testConnectionOnCheckout: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity

logging:
  level:
    com.example: DEBUG
